-- M0:书籍与章节(需求文档 §6.4 数据模型草图)
-- schema 变更一律走 Flyway 迁移,禁止手改(D-17,ADR-0003)

CREATE TABLE book
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      TEXT        NOT NULL,
    author     TEXT,
    language   TEXT,
    cover_path TEXT, -- 相对 storage root 的路径,如 covers/<hash>.jpg;无封面为 NULL
    file_hash  VARCHAR(64) NOT NULL, -- EPUB 文件 SHA-256 hex;同 hash 幂等(D-30)
    file_size  BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_book_file_hash UNIQUE (file_hash)
);

-- 章节 = 有正文的内容文件,按阅读顺序平铺(D-40);嵌套目录不入库
-- (book_id,seq) 唯一索引同时覆盖按 book 查询,无需单列 book_id 索引)
CREATE TABLE chapter
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     BIGINT NOT NULL REFERENCES book (id) ON DELETE CASCADE,
    seq         INT    NOT NULL, -- spine 阅读顺序,从 1 起
    title       TEXT,
    href        TEXT   NOT NULL, -- EPUB 内原文路径(如 OEBPS/ch1.xhtml)
    content     TEXT   NOT NULL, -- 清洗后的纯文本(D-40,ADR-0005)
    text_length INT    NOT NULL, -- content 字符数(供预算/展示)
    CONSTRAINT uk_chapter_book_seq UNIQUE (book_id, seq)
);
