-- M1:划线与阅读进度(需求文档 §6.4 / M1 spec)
-- schema 变更一律走 Flyway 迁移,禁止手改(D-17,ADR-0003)
-- updated_at 一律服务器时钟(DB now()),客户端不传时间戳(D-19)
-- 外键按级联删除建,为 FR-104 完整级联(M3/M4 表齐后一并交付)预留

CREATE TABLE highlight
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id    BIGINT      NOT NULL REFERENCES book (id) ON DELETE CASCADE,
    cfi        TEXT        NOT NULL, -- EPUB CFI(foliate-js 产出,区间 CFI)
    text       TEXT        NOT NULL, -- 选中文字快照(展示与 CFI 失效降级文案用)
    note       TEXT, -- 备注(可空)
    color      TEXT, -- 颜色(可空)
    device     TEXT, -- 端上自报设备标识(仅展示/追溯,不参与裁决)
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_highlight_book_id ON highlight (book_id);

-- 每本书单行进度:book_id 即主键,upsert 以它冲突合并(D-24)
CREATE TABLE reading_progress
(
    book_id    BIGINT PRIMARY KEY REFERENCES book (id) ON DELETE CASCADE,
    cfi        TEXT   NOT NULL,
    percent    INT    NOT NULL CHECK (percent BETWEEN 0 AND 100), -- 0-100 整数,仅展示用;接续定位靠 CFI
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
