-- M3:AI 会话与消息(需求文档 §6.4 / M3 spec · FR-301/303/304,D-32/D-33)
-- schema 变更一律走 Flyway 迁移,禁止手改(D-17,ADR-0003)
-- updated_at 服务器时钟(DB now()),新消息/重命名时刷新 = "最近活跃会话"的裁决字段(不反查消息表)

CREATE TABLE chat_session
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id    BIGINT REFERENCES book (id) ON DELETE CASCADE, -- 可空:跨书会话(M4 预留,D-33;级联不触及空 book_id)
    title      TEXT   NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_chat_session_book_id ON chat_session (book_id);
CREATE INDEX idx_chat_session_updated_at ON chat_session (updated_at); -- 最近活跃排序

-- refs:引用来源(jsonb;首版 = 选中文字引用 + 章节引用,形状实现定,M3 spec · Further Notes)
CREATE TABLE chat_message
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES chat_session (id) ON DELETE CASCADE,
    role       TEXT   NOT NULL, -- user / assistant
    content    TEXT   NOT NULL,
    refs       JSONB, -- 引用来源数组,可空;M4 跨书场景按书籍存在性降级渲染(D-33)
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_chat_message_session_id ON chat_message (session_id);
