-- M4:向量块与嵌入任务(需求文档 §6.4 / M4 spec · FR-302/104,D-36/R-3)
-- schema 变更一律走 Flyway 迁移,禁止手改(D-17,ADR-0003)
-- 维度与检索策略见 ADR-0008:embedding 列 vector 不带 typmod(维度随嵌入模型),
-- 个人量级顺序 cosine 扫描,ANN 索引延后

CREATE EXTENSION IF NOT EXISTS vector;

-- 向量块:章节正文切块后嵌入的文本单位(术语见 CONTEXT.md)
-- seq = 块在章内的序号(1 起,每章独立推进,M4-01);chapter_id 溯源所属章节
CREATE TABLE document_chunk
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     BIGINT NOT NULL REFERENCES book (id) ON DELETE CASCADE,
    chapter_id  BIGINT NOT NULL REFERENCES chapter (id) ON DELETE CASCADE,
    seq         INT    NOT NULL,
    content     TEXT   NOT NULL,
    token_count INT    NOT NULL,
    embedding   vector, -- 不带 typmod(R-3):同书全部块由同一模型一次任务嵌入,维度天然一致
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (chapter_id, seq)
);

CREATE INDEX idx_document_chunk_book_id ON document_chunk (book_id); -- 表内按书过滤是检索主路径

-- 嵌入任务:对一本书全量生成向量块的后台作业(有状态与进度,失败可重试)
-- 表内可存历史(重试/重嵌入各建新行),对外每书读最新一条;updated_at 服务器时钟(D-19)
CREATE TABLE embedding_job
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     BIGINT NOT NULL REFERENCES book (id) ON DELETE CASCADE,
    model       TEXT   NOT NULL,
    status      TEXT   NOT NULL, -- pending / running / done / failed
    chunk_done  INT    NOT NULL DEFAULT 0,
    chunk_total INT    NOT NULL DEFAULT 0,
    error       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_embedding_job_book_id ON embedding_job (book_id);
